name: Full CI process
on:
  push:
    branches:
      - '*'
      - '!main'
      - '!master'
env:
  ES_HTTP_PORT: 9209
jobs:
  symfony:
    name: Symfony (PHP ${{ matrix.php-versions }})
    # https://hub.docker.com/_/ubuntu/
    runs-on: ubuntu-20.04
    services:
      # https://docs.docker.com/samples/library/mysql/
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      # https://hub.docker.com/_/elasticsearch/
      elasticsearch:
        image: elasticsearch:6.8.10
        ports:
          - 9209:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.0', '8.1']
    steps:
      # —— Check Elasticsearch 🔎 ——————————————————————————————————————————————
      - name: Check the Elasticsearch connection from runner host
        run: |
          curl -fsSL "http://localhost:$ES_HTTP_PORT"
          curl -fsSL "http://localhost:$ES_HTTP_PORT/_cluster/health?pretty"

      # —— Setup Github actions 🐙 —————————————————————————————————————————————
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring
        env:
          update: true

      - name: Check PHP Version
        run: php -v

      # https://github.com/zhulik/redis-action (community)
      - name: Setup Redis with zhulik/redis-action
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: '5'

      ## —— Yarn 🐱 ————————————————————————————————————————————————————————————
      - name: Yarn install
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          #registry-url: npm.fontawesome.com
      - run: yarn install
          #env:
        #NODE_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Yarn build
        run: yarn build

      # —— Composer 🧙‍️ —————————————————————————————————————————————————————————

      # Remove vendor and composer.lock before run composer install (~70% of the builds are failing without this)
      - name:  Install Composer dependencies 
        run: rm composer.lock && composer install --no-cache

      # —— Symfony 🎵 ——————————————————————————————————————————————————————————
      - name: Check bin/console
        run: php bin/console

      - name: Check the Symfony console
        run: |
          php bin/console about

      # ## —— Coding standards For php-cs-fixer  ————————————————————————————————————————————————
      # - name: Coding standards checks (php_codesniffer + php-cs-fixer)
      #   run: make cs
      #   if: matrix.php-versions == '8.0'

      # ## —— Static analysis  —————————————————————————————————————————————————
      # - name: Static analysis of PHP code (PHPStan)
      #   run: |
      #     php bin/console about --env=prod
     

      ## —— Tests ✅ ———————————————————————————————————————————————————————————
      # We use the dev env here
      - name: Setup Database
        run: |
          php bin/console about --env=dev


      - name: Load Doctrine fixtures
        run: |
          php bin/console doctrine:fixtures:load
  
      # - name: Run functionnal and unit tests
      #   run: |
      #     cp phpunit.xml.ci phpunit.xml
      #     ./vendor/bin/phpunit --testsuite='main'